version: '3.5'

services:

  emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:392.0.0-emulators
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085
    ports:
      - 8085:8085
