name: build-lint-test

on:
  workflow_call:

env:
  PUBSUB_EMULATOR_HOST: localhost:8085

jobs:
  build-lint-test:
    strategy:
      fail-fast: true
      matrix:
        nestjs-version:
          - 7
          - 8
          - 9
          - 10
        nodejs-version:
          - 16
          - 18
          - 20
        include:
          - nestjs-version: 7
            rxjs-version: 6
          - nestjs-version: 8
            rxjs-version: 7
          - nestjs-version: 9
            rxjs-version: 7
          - nestjs-version: 10
            rxjs-version: 7

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # start emulator

      - uses: google-github-actions/setup-gcloud@v0
        with:
          install_components: 'beta,pubsub-emulator'
      - run: gcloud beta emulators pubsub start --project=testproject --host-port=0.0.0.0:8085 &

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs-version }}
      - run: npm ci
      - run: |
          npm i @types/node@${{ matrix.nodejs-version }} \
                @nestjs/core@${{ matrix.nestjs-version }} \
                @nestjs/common@${{ matrix.nestjs-version }} \
                @nestjs/microservices@${{ matrix.nestjs-version }} \
                rxjs@${{ matrix.rxjs-version }} \
                -D
      - run: npm run lint
      - uses: actions/cache@v3
        with:
          path: coverage
          key: ${{ github.sha }}-${{ matrix.nestjs-version }}-${{ matrix.nodejs-version }}
      - run: npm t
      - run: npm run build
