name: build-lint-test

on:
  workflow_call:

env:
  PUBSUB_EMULATOR_HOST: localhost:8085

jobs:
  build-lint-test:
    strategy:
      fail-fast: false
      matrix:
        nestjs-version:
          - "8"
          - "9"
          - "10"
          - "11"
        nodejs-version:
          - 20
          - 22
        include:
          - nestjs-version: 8
            typescript-version: 4
          - nestjs-version: 9
            typescript-version: 4
          - nestjs-version: 10
            typescript-version: 5
          - nestjs-version: 11
            typescript-version: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # start emulator

      - uses: google-github-actions/setup-gcloud@v0
        with:
          install_components: 'beta,pubsub-emulator'
      - run: gcloud beta emulators pubsub start --project=testproject --host-port=0.0.0.0:8085 &

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs-version }}
      - run: npm ci
      - run: |
          npm i @nestjs/core@${{ matrix.nestjs-version }} \
                @nestjs/common@${{ matrix.nestjs-version }} \
                @nestjs/microservices@${{ matrix.nestjs-version }} \
                @types/node@${{ matrix.nodejs-version }} \
                typescript@${{ matrix.typescript-version }} \
                -D
      - run: npm run lint
      - uses: actions/cache@v3
        with:
          path: coverage
          key: ${{ github.sha }}-${{ matrix.nestjs-version }}-${{ matrix.nodejs-version }}
      - run: npm t
      - run: npm run build
